# Prometheus configuration for Stock Market Monitor

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s
  external_labels:
    monitor: 'stock-market-monitor'
    environment: 'production'

rule_files:
  - "rules/*.yml"
  - "alerts/*.yml"

scrape_configs:
  # Stock Monitor Application
  - job_name: 'stock-monitor'
    static_configs:
      - targets: ['stock_monitor_app_desktop:8080']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true
    
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    
  # Node Exporter (system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 15s
    
  # PostgreSQL Exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']
    scrape_interval: 30s
    
  # Redis Exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']
    scrape_interval: 30s
    
  # Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['localhost:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    
  # Stock Monitor Custom Metrics
  - job_name: 'stock-monitor-metrics'
    static_configs:
      - targets: ['stock_monitor_app_desktop:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    honor_labels: true
    relabel_configs:
      - source_labels: [__name__]
        regex: 'stock_.*'
        target_label: 'component'
        replacement: 'stock_monitor'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093