# Stock Market Monitoring System - Desktop Optimized Configuration
# This configuration is optimized for desktop environments with higher resources

# Database Configuration
database:
  type: "dual"  # "postgresql", "influxdb", or "dual"
  host: "postgres"
  port: 5432
  name: "stock_monitor"
  user: "stock_user"
  password: "${POSTGRES_PASSWORD:-your_postgres_password}"
  
  # Desktop optimizations
  pool_size: 20
  max_overflow: 50
  pool_timeout: 30
  pool_recycle: 3600
  
  # InfluxDB specific settings
  influxdb:
    url: "http://influxdb:8086"
    token: "${INFLUXDB_TOKEN:-your_influxdb_token}"
    org: "stock_monitor"
    bucket: "market_data"
    batch_size: 10000
    flush_interval: 1000

# Redis Configuration
redis:
  host: "redis"
  port: 6379
  password: ""
  db: 0
  # Desktop optimizations
  max_connections: 100
  connection_pool_kwargs:
    max_connections: 100
    retry_on_timeout: true
    socket_timeout: 30
    socket_connect_timeout: 30

# API Keys (Get these from respective services)
api_keys:
  alpha_vantage: "${ALPHA_VANTAGE_API_KEY:-your_alpha_vantage_key}"
  polygon: "${POLYGON_API_KEY:-your_polygon_key}"
  finnhub: "${FINNHUB_API_KEY:-your_finnhub_key}"
  news_api: "${NEWS_API_KEY:-your_news_api_key}"
  quandl: "your_quandl_key"
  iex_cloud: "your_iex_cloud_key"
  fred: "${FRED_API_KEY:-your_fred_api_key}"
  # Additional API keys for multi-asset data
  fixer: "${FIXER_API_KEY:-your_fixer_api_key}"
  exchangerate: "your_exchangerate_api_key"
  coinmarketcap: "your_cmc_api_key"
  coingecko: "${COINGECKO_API_KEY:-your_coingecko_api_key}"
  binance: "your_binance_api_key"

# Data Collection Settings - Desktop Enhanced
data_collection:
  # Update intervals (in seconds) - faster for desktop
  stock_data_interval: 30
  commodity_data_interval: 60
  forex_data_interval: 30  # Fast updates for forex
  crypto_data_interval: 15  # Very fast for crypto (24/7 markets)
  news_interval: 300
  sentiment_interval: 600
  economic_data_interval: 900
  
  # Rate limiting - higher for desktop
  max_requests_per_minute: 200
  max_requests_per_hour: 5000
  max_concurrent_requests: 20
  
  # Exchanges to monitor
  exchanges:
    us:
      - "NYSE"
      - "NASDAQ"
      - "AMEX"
      - "BATS"
      - "IEX"
    europe:
      - "LSE"
      - "FRA"
      - "AMS"
      - "SWX"
      - "MIL"
      - "BME"
    asia:
      - "TSE"
      - "HKG"
      - "SSE"
      - "SZSE"
      - "NSE"
      - "BSE"
      - "KRX"
      - "TPE"
    others:
      - "TSX"  # Toronto
      - "ASX"  # Australia
      - "JSE"  # Johannesburg

# Enhanced Commodities tracking
commodities:
  metals:
    - "GC=F"  # Gold
    - "SI=F"  # Silver
    - "PL=F"  # Platinum
    - "PA=F"  # Palladium
    - "HG=F"  # Copper
    - "ALI=F" # Aluminum
  energy:
    - "CL=F"  # Crude Oil
    - "NG=F"  # Natural Gas
    - "BZ=F"  # Brent Oil
    - "RB=F"  # Gasoline
    - "HO=F"  # Heating Oil
  agriculture:
    - "ZC=F"  # Corn
    - "ZS=F"  # Soybeans
    - "ZW=F"  # Wheat
    - "KC=F"  # Coffee
    - "CT=F"  # Cotton
    - "SB=F"  # Sugar
    - "CC=F"  # Cocoa
  currencies:
    - "EURUSD=X"
    - "GBPUSD=X"
    - "USDJPY=X"
    - "USDCAD=X"
    - "AUDUSD=X"

# Enhanced Technical Indicators
technical_indicators:
  rsi:
    period: 14
    overbought: 70
    oversold: 30
  macd:
    fast_period: 12
    slow_period: 26
    signal_period: 9
  bollinger_bands:
    period: 20
    std_dev: 2
  moving_averages:
    - 5
    - 10
    - 20
    - 50
    - 100
    - 200
  stochastic:
    k_period: 14
    d_period: 3
  williams_r:
    period: 14
  cci:
    period: 20
  adx:
    period: 14

# Enhanced Alert Settings
alerts:
  price_change_threshold: 3.0  # Percentage (more sensitive)
  volume_spike_threshold: 150.0  # Percentage
  volatility_threshold: 2.5  # Standard deviations
  correlation_threshold: 0.75
  rsi_overbought: 75
  rsi_oversold: 25
  
  # Enhanced notification methods
  email:
    enabled: false
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    username: "your_email@gmail.com"
    password: "${EMAIL_PASSWORD:-your_app_password}"
    rate_limit: 10  # max emails per hour
  
  telegram:
    enabled: false
    bot_token: "${TELEGRAM_BOT_TOKEN:-your_bot_token}"
    chat_id: "your_chat_id"
  
  webhook:
    enabled: false
    url: "https://your-webhook-url.com"
  
  desktop:
    enabled: true
    notification_level: "important"  # all, important, critical
    sound_enabled: true
    popup_duration: 10  # seconds

# Enhanced Portfolio Management
portfolio:
  default_currency: "USD"
  rebalancing_frequency: "weekly"  # more frequent
  risk_tolerance: "moderate"  # conservative, moderate, aggressive
  max_position_size: 0.15  # 15% of portfolio
  stop_loss_percentage: 0.03  # 3%
  take_profit_percentage: 0.10  # 10%
  # Desktop-specific features
  real_time_pnl: true
  tax_loss_harvesting: true
  dividend_tracking: true
  cost_basis_method: "fifo"  # fifo, lifo, specific_lot

# Enhanced ML and Analytics
ml:
  anomaly_detection:
    enabled: true
    model_type: "isolation_forest"
    contamination: 0.05
    update_frequency: "hourly"  # more frequent
    features: ["price", "volume", "volatility", "technical_indicators"]
  
  sentiment_analysis:
    enabled: true
    model_type: "vader"
    update_frequency: "every_30_minutes"
    sources: ["news", "social_media", "earnings_calls"]
  
  correlation_analysis:
    enabled: true
    lookback_period: 60  # days (longer for desktop)
    update_frequency: "hourly"
    correlation_threshold: 0.7
  
  predictive_models:
    enabled: true
    models: ["lstm", "random_forest", "xgboost"]
    prediction_horizon: 5  # days
    retrain_frequency: "weekly"

# Enhanced Web Dashboard
dashboard:
  host: "0.0.0.0"
  port: 8080
  debug: false
  reload: false
  workers: 4  # more workers for desktop
  
  # Authentication
  auth:
    enabled: true
    secret_key: "${SECRET_KEY:-your_secret_key_here}"
    token_expire_minutes: 120  # longer for desktop
  
  # Desktop features
  features:
    real_time_charts: true
    advanced_analytics: true
    portfolio_optimization: true
    risk_analysis: true
    news_sentiment: true
    economic_calendar: true
    screener: true
    backtesting: true

# Enhanced Prometheus Monitoring
prometheus:
  enabled: true
  port: 9090
  metrics_path: "/metrics"
  scrape_interval: "10s"  # faster for desktop
  
  # Custom metrics
  custom_metrics:
    - "stock_price"
    - "portfolio_value"
    - "alert_count"
    - "api_request_count"
    - "data_collection_latency"
    - "prediction_accuracy"
    - "system_performance"

# Enhanced Grafana
grafana:
  enabled: true
  port: 3000
  admin_user: "admin"
  admin_password: "admin"
  # Desktop enhancements
  plugins:
    - "grafana-clock-panel"
    - "grafana-worldmap-panel"
    - "grafana-piechart-panel"
    - "grafana-plotly-panel"

# Enhanced Logging
logging:
  level: "INFO"
  format: "json"
  file: "logs/stock_monitor.log"
  max_size: "500MB"  # larger for desktop
  backup_count: 10
  # Desktop enhancements
  structured_logging: true
  log_rotation: "daily"
  log_compression: true

# Desktop Performance Optimization
performance:
  max_workers: 12  # more workers
  memory_limit: "8GB"  # higher limit
  cpu_limit: 0.9  # 90% of available CPU
  
  # Enhanced caching
  cache_ttl: 180  # 3 minutes
  max_cache_size: "2GB"  # larger cache
  cache_compression: true
  
  # Database optimization
  batch_size: 5000  # larger batches
  connection_pool_size: 25  # more connections
  query_timeout: 60  # seconds
  
  # Async processing
  async_enabled: true
  max_concurrent_tasks: 50
  task_timeout: 300  # 5 minutes

# Enhanced Timezone and Market Hours
timezone:
  default: "UTC"
  markets:
    us: "America/New_York"
    europe: "Europe/London"
    asia: "Asia/Tokyo"
    australia: "Australia/Sydney"
    canada: "America/Toronto"
  
  # Extended hours trading
  extended_hours:
    enabled: true
    pre_market_start: "04:00"
    after_hours_end: "20:00"

# Enhanced Economic Calendar
economic_calendar:
  enabled: true
  sources:
    - "investing.com"
    - "fxstreet.com"
    - "marketwatch.com"
    - "bloomberg.com"
  update_frequency: "every_30_minutes"
  event_types:
    - "GDP"
    - "CPI"
    - "Employment"
    - "Interest Rate"
    - "Earnings"
    - "Fed Speeches"
    - "Economic Indicators"
  importance_filter: "medium"  # low, medium, high

# Desktop-specific features
desktop:
  # System tray integration
  system_tray:
    enabled: true
    show_notifications: true
    quick_actions: ["dashboard", "alerts", "portfolio"]
  
  # Keyboard shortcuts
  hotkeys:
    enabled: true
    toggle_dashboard: "Ctrl+Shift+D"
    emergency_stop: "Ctrl+Shift+X"
    quick_portfolio: "Ctrl+Shift+P"
  
  # Auto-start options
  startup:
    enabled: false
    minimize_to_tray: true
    delay_seconds: 30
  
  # Desktop widgets
  widgets:
    enabled: true
    portfolio_widget: true
    market_overview: true
    alert_ticker: true

# Advanced Features (Desktop only)
advanced:
  # Machine Learning Models
  ml_models:
    enabled: true
    gpu_acceleration: false  # set to true if GPU available
    model_path: "models/"
    auto_training: true
  
  # Data Export
  export:
    enabled: true
    formats: ["csv", "excel", "json", "parquet"]
    scheduled_exports: true
    cloud_backup: false
  
  # API Rate Optimization
  api_optimization:
    intelligent_caching: true
    request_batching: true
    failover_sources: true
    load_balancing: true
  
  # Security Features
  security:
    encryption_at_rest: true
    secure_api_keys: true
    audit_logging: true
    backup_encryption: true
