# Grafana Datasource Configuration
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      queryTimeout: 60s
      timeInterval: 5s
    version: 1

  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: financial_data
    user: admin
    secureJsonData:
      password: password
    editable: true
    version: 1

  - name: Alertmanager
    type: alertmanager
    access: proxy
    url: http://alertmanager:9093
    editable: true
    version: 1